include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - sort_pub_dependencies
    - unused_imports

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
